<dependecies>
  
  <!-- https://mvnrepository.com/artifact/oracle/ojdbc6 -->
  <dependency>
  <groupId>oracle</groupId>
  <artifactId>ojdbc6</artifactId>
  <version>11.2.0.3</version>
  <scope>system</scope>
  </dependency>

</dependecies>





