spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: RM550893
    password : 070704
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
server:
  port: 80